### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by saraswat** [finos/legend-pure#497]
### Steps to Reproduce:
 1. Clone the repo.
 2. Edit the main pom.xml to remove   `<module>legend-pure-ide-light</module>` -- this is my attempt to operationalize the comment in the readme:
 >Pure IDE has a web application component which requires Node 14.17.1+ and Yarn 1.22.10. Make sure you have these set up in your development environment, otherwise, you would need to exclude the build step for this web application in legend-pure-ide-light module.

(I looked for what I could exclude in `legend-pure-ide-light/pom.xml`, couldn't find anything. Is this particular comment out of date?)
3. Run `mvn install`

### Expected Result:
successful build

### Actual Result:
failure. See attached log.

### Environment:
`mvn](url) --version`:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/vijaysaraswat/Downloads/apache-maven-3.6.3
Java version: 11.0.14, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
```

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...
[build-fail-log.txt](https://github.com/finos/legend-pure/files/8340845/build-fail-log.txt)

**Comment by aziemchawdhary-gs** [comment]
Rather than deleting the module from the root pom, you can exclude the module from the build:

mvn clean install -pl \!legend-pure-ide-light 

(note in bash the ! needs to be escaped using the backslash)

**Comment by saraswat** [comment]
Thanks, did that. Blew away my checkout. Did a fresh `git clone`. Still get:

```
Tests run: 14, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 0.02 sec <<< FAILURE! - in org.finos.legend.pure.m4.primitives.TestPureDate
testAddNanoseconds(org.finos.legend.pure.m4.primitives.TestPureDate)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem: 
	The declared package "org.finos.legend.pure.m4.coreinstance.primitive.date" does not match the expected package "org.finos.legend.pure.m4.primitives"

	at org.finos.legend.pure.m4.primitives.TestPureDate.<init>(TestPureDate.java:15)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org
...
```

**Comment by saraswat** [comment]
Actually, doing a `mvn pre-clean clean post-clean` before the `mvn install -pl \!legend-pure-ide-light` has helped. Compilation is progressing. Let's see if it terminates successfully.
